import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],

  theme: {
    extend: {
      colors: {
        background: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#131b2e",
        "surface-container-highest": "#d3e4fe",
        surface: "#f8f9ff",
        "on-error": "#ffffff",
        "on-surface": "#0b1c30",
        "on-primary-container": "#a8b8ff",
        "error-container": "#ffdad6",
        "surface-variant": "#d3e4fe",
        "on-surface-variant": "#444653",
        "surface-container-high": "#dce9ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#dae2fd",
        "primary-fixed": "#dde1ff",
        "secondary-fixed": "#dbe1ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#001453",
        "primary-fixed-dim": "#b8c4ff",
        "on-primary-fixed-variant": "#173bab",
        secondary: "#0051d5",
        "secondary-fixed-dim": "#b4c5ff",
        primary: "#00288e",
        "on-secondary-container": "#fefcff",
        "tertiary-fixed-dim": "#bec6e0",
        "secondary-container": "#316bf3",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "on-background": "#0b1c30",
        "surface-tint": "#3755c3",
        "inverse-surface": "#213145",
        "inverse-primary": "#b8c4ff",
        "on-tertiary-fixed-variant": "#3f465c",
        "primary-container": "#1e40af",
        tertiary: "#2d3449",
        "tertiary-container": "#434b60",
        outline: "#757684",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "surface-container": "#e5eeff",
        "on-tertiary-container": "#b4bbd5",
        "on-secondary-fixed-variant": "#003ea8",
        "outline-variant": "#c4c5d5",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#00174b",
      },
      spacing: {
        "space-xxs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "3rem",
        "gutter-desktop": "1rem",
        "panel-split-width": "26rem",
        "nav-rail-width": "4.5rem",
        "nav-expanded-width": "15rem",
      },
      fontFamily: {
        "metric-display": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "code-tabular": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "metric-display": ["26px", { lineHeight: "32px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "title-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "code-tabular": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
