import type { BillingEvent, InvoicePreview, Subscription, SubscriptionChange, SubscriptionPlan } from "./types";

export const subscriptionStats = [
  { label: "ACTIVE SUBSCRIPTIONS", value: "24", icon: "autorenew" },
  { label: "MRR", value: "$42,850", icon: "payments" },
  { label: "ARR", value: "$514,200", icon: "query_stats" },
  { label: "RENEWING THIS MONTH", value: "3", icon: "event_repeat" },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  { id: "enterprise-core-pro", name: "Enterprise Core Plan Pro", unitPrice: 490 },
  { id: "enterprise-support-plus", name: "Enterprise Support Plus", unitPrice: 720 },
  { id: "cloud-analytics-pro", name: "Cloud Analytics Pro", unitPrice: 500 },
];

export const subscriptions: Subscription[] = [
  {
    id: "SUB-1042",
    customer: "Acme Corporation",
    plan: "Enterprise Core Plan Pro",
    status: "Active",
    paymentStatus: "Paid / Up to Date",
    billingInterval: "Monthly",
    quantity: 10,
    unitPrice: 490,
    recurringValue: 4900,
    recurringLabel: "MRR",
    mrr: 4900,
    arr: 58800,
    startDate: "05 Sep 2026",
    nextBillingDate: "05 Oct 2026",
    renewalDate: "05 Sep 2027",
    contractTerm: "12 months",
    sourceOrder: "ORD-1042",
    sourceQuote: "Q-1042",
  },
  {
    id: "SUB-1038",
    customer: "Nova Systems",
    plan: "Enterprise Support Plus",
    status: "Active",
    paymentStatus: "Paid / Up to Date",
    billingInterval: "Annual",
    quantity: 25,
    unitPrice: 720,
    recurringValue: 18000,
    recurringLabel: "ARR",
    mrr: 1500,
    arr: 18000,
    startDate: "18 Jul 2026",
    nextBillingDate: "18 Jul 2027",
    renewalDate: "18 Jul 2027",
    contractTerm: "12 months",
    sourceOrder: "ORD-1038",
    sourceQuote: "Q-1038",
  },
  {
    id: "SUB-1027",
    customer: "Vertex Labs",
    plan: "Cloud Analytics Pro",
    status: "Pending Cancellation",
    paymentStatus: "Paid / Up to Date",
    billingInterval: "Quarterly",
    quantity: 15,
    unitPrice: 500,
    recurringValue: 7500,
    recurringLabel: "per quarter",
    mrr: 2500,
    arr: 30000,
    startDate: "12 May 2026",
    nextBillingDate: "12 Nov 2026",
    renewalDate: "12 May 2027",
    contractTerm: "12 months",
    sourceOrder: "ORD-1027",
    sourceQuote: "Q-1027",
  },
  {
    id: "SUB-1019",
    customer: "Orion Manufacturing",
    plan: "Enterprise Core Plan",
    status: "Active",
    paymentStatus: "Paid / Up to Date",
    billingInterval: "Annual",
    quantity: 50,
    unitPrice: 840,
    recurringValue: 42000,
    recurringLabel: "ARR",
    mrr: 3500,
    arr: 42000,
    startDate: "02 Apr 2026",
    nextBillingDate: "02 Apr 2027",
    renewalDate: "02 Apr 2027",
    contractTerm: "12 months",
    sourceOrder: "ORD-1019",
    sourceQuote: "Q-1019",
  },
  {
    id: "SUB-1008",
    customer: "Helio Retail Group",
    plan: "Cloud Analytics Pro",
    status: "Past Due",
    paymentStatus: "Past Due",
    billingInterval: "Monthly",
    quantity: 8,
    unitPrice: 500,
    recurringValue: 4000,
    recurringLabel: "MRR",
    mrr: 4000,
    arr: 48000,
    startDate: "15 Mar 2026",
    nextBillingDate: "15 Sep 2026",
    renewalDate: "15 Mar 2027",
    contractTerm: "12 months",
    sourceOrder: "ORD-1008",
    sourceQuote: "Q-1008",
  },
];

export const billingEvents: BillingEvent[] = [
  { id: "evt-start", date: "05 Sep 2026", label: "Subscription Started", amount: 4900, status: "Completed" },
  { id: "evt-inv-2042", date: "05 Oct 2026", label: "Invoice #INV-2042", amount: 4900, status: "Upcoming" },
  { id: "evt-nov", date: "05 Nov 2026", label: "Recurring Invoice", amount: 4900, status: "Scheduled" },
  { id: "evt-dec", date: "05 Dec 2026", label: "Recurring Invoice", amount: 4900, status: "Scheduled" },
  { id: "evt-jan", date: "05 Jan 2027", label: "Recurring Invoice", amount: 4900, status: "Scheduled" },
];

export const invoicePreview: InvoicePreview[] = [
  { id: "INV-2041", date: "05 Sep 2026", amount: 4900, status: "Paid" },
  { id: "INV-2042", date: "05 Oct 2026", amount: 4900, status: "Upcoming" },
  { id: "INV-2043", date: "05 Nov 2026", amount: 4900, status: "Scheduled" },
];

export const subscriptionChange: SubscriptionChange = {
  currentQuantity: 10,
  requestedQuantity: 15,
  currentMonthlyAmount: 4900,
  newMonthlyAmount: 7350,
  estimatedProratedAdjustment: 408.33,
};
