"use client";

import React, { useState } from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { RecommendationCard } from "@/components/RecommendationCard";
import { Sparkles, Eye, X } from "lucide-react";
import type { CounterfactualRecommendation } from "@/types/counterfactual.types";
import { Button } from "@/components/ui/button";

interface CounterfactualCardProps {
  recommendations: CounterfactualRecommendation[];
  isLoading?: boolean;
}

export function CounterfactualCard({
  recommendations = [],
  isLoading = false,
}: CounterfactualCardProps) {
  const [activePreview, setActivePreview] = useState<CounterfactualRecommendation | null>(null);

  return (
    <Card className="rounded-xl border border-indigo-200/80 bg-white dark:bg-slate-900/60 shadow-sm">
      <CardHeader className="border-b border-indigo-100/60 pb-3 flex flex-row items-center justify-between">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-indigo-600" />
            <CardTitle className="text-sm font-semibold text-slate-900 dark:text-slate-50">
              Counterfactual Prescriptive Recommendations
            </CardTitle>
          </div>
          <CardDescription className="mt-0.5">
            Minimal mathematical adjustments generated by the Counterfactual Engine to unlock Fast-Track Auto Approval.
          </CardDescription>
        </div>
      </CardHeader>

      <CardContent className="pt-4 space-y-4">
        {/* Active Live Preview Banner */}
        {activePreview && (
          <div className="p-4 rounded-xl bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 flex items-start justify-between gap-4 animate-in fade-in-50">
            <div className="space-y-1 text-xs">
              <div className="flex items-center gap-2">
                <Eye className="h-4 w-4 text-blue-600" />
                <span className="font-bold text-blue-900">
                  Simulated Scenario Applied to Preview:
                </span>
                <span className="font-semibold text-blue-700">{activePreview.title}</span>
              </div>
              <p className="text-slate-600">
                Expected outcome:{" "}
                <strong className="text-emerald-700">{activePreview.expectedResult}</strong> with{" "}
                <strong className="text-slate-800">
                  Projected Risk Score: {activePreview.projectedRiskScore}
                </strong>{" "}
                and Revenue Concession: {activePreview.revenueImpactFormatted}.
              </p>
              <p className="text-[11px] text-slate-400">
                Note: This is a non-destructive client preview. Original quotation values in PostgreSQL remain unchanged.
              </p>
            </div>

            <Button
              size="sm"
              variant="ghost"
              onClick={() => setActivePreview(null)}
              className="h-7 w-7 p-0 text-slate-400 hover:text-slate-700"
            >
              <X className="h-4 w-4" />
            </Button>
          </div>
        )}

        {isLoading ? (
          <div className="py-8 text-center text-xs text-slate-400">
            Evaluating counterfactual permutations...
          </div>
        ) : recommendations.length === 0 ? (
          <div className="py-6 text-center text-xs text-slate-400">
            No counterfactual recommendations required. This quotation already complies with commercial guidelines.
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {recommendations.map((rec) => (
              <RecommendationCard
                key={rec.id}
                recommendation={rec}
                isApplied={activePreview?.id === rec.id}
                onApplyPreview={(applied) => setActivePreview(applied)}
              />
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
