import { ApprovalItem } from "@/types/approval";

export const MOCK_APPROVAL_ITEMS: ApprovalItem[] = [
  {
    id: "appr-1042",
    dealId: "Q-1042",
    customer: "Acme Corporation",
    customerGlobalId: "AC-88219",
    value: "$18,300.00",
    rawNumericValue: 18300,
    riskScore: 72,
    riskCategory: "High",
    currentStage: "Finance Review",
    submittedTimeAgo: "12 min ago",
    submittedExactTime: "12:02 PM",
    status: "Awaiting Review",
    priority: "High",
    quoteUrl: "/",
    requestedBy: {
      name: "James Carter",
      role: "Sales Manager",
      avatarUrl: "/james-carter.jpg",
    },
    reasons: [
      {
        id: "rs-1",
        title: "Service Discount Anomaly",
        requestedValue: "18%",
        allowedLimit: "10%",
        exceptionText: "8% above configured threshold",
        severity: "warning",
      },
      {
        id: "rs-2",
        title: "Margin Below Target",
        requestedValue: "36%",
        allowedLimit: "40%",
        exceptionText: "4% below preferred threshold",
        severity: "high",
      },
    ],
    financials: {
      subtotal: "$20,250.00",
      discount: "-$3,420.00",
      estimatedTax: "$1,470.00",
      netTotal: "$18,300.00",
      estMargin: "$6,588.00",
      marginPercentage: "36%",
    },
    workflow: [
      {
        stepNumber: 1,
        role: "Sales Manager",
        assignee: "James Carter",
        status: "Completed",
        statusLabel: "Auto-authorized",
        delegatedLimitOrTrigger: "Delegated Limit: 15%",
      },
      {
        stepNumber: 2,
        role: "Finance Review",
        assignee: "Marcus Vance",
        status: "Current",
        statusLabel: "Required",
        delegatedLimitOrTrigger: "Triggered by service discount anomaly (>10%)",
      },
      {
        stepNumber: 3,
        role: "VP Commercial",
        assignee: "Elena Rostova",
        status: "Pending",
        statusLabel: "Pending",
        delegatedLimitOrTrigger: "Only triggered if required after finance review",
      },
    ],
    history: [
      {
        id: "hist-1",
        time: "12:02 PM",
        description: "James Carter submitted the quotation for approval.",
        actor: "James Carter",
      },
      {
        id: "hist-2",
        time: "11:58 AM",
        description: "Risk engine detected discount governance exception.",
        actor: "Governance Engine",
      },
      {
        id: "hist-3",
        time: "11:57 AM",
        description: "Quote Q-1042 updated.",
        actor: "James Carter",
      },
    ],
  },
  {
    id: "appr-1029",
    dealId: "Q-1029",
    customer: "Orion Manufacturing",
    customerGlobalId: "OR-99120",
    value: "$96,400.00",
    rawNumericValue: 96400,
    riskScore: 68,
    riskCategory: "High",
    currentStage: "Commercial Review",
    submittedTimeAgo: "28 min ago",
    submittedExactTime: "11:46 AM",
    status: "Awaiting Review",
    priority: "High",
    requestedBy: {
      name: "David Vance",
      role: "Enterprise Account Exec",
    },
    reasons: [
      {
        id: "rs-3",
        title: "Extended Payment Terms",
        requestedValue: "Net 90",
        allowedLimit: "Net 45",
        exceptionText: "45 days beyond standard corporate governance",
        severity: "warning",
      },
      {
        id: "rs-4",
        title: "Margin Threshold Violation",
        requestedValue: "24%",
        allowedLimit: "30%",
        exceptionText: "6% below commercial minimum threshold",
        severity: "high",
      },
    ],
    financials: {
      subtotal: "$118,500.00",
      discount: "-$22,100.00",
      estimatedTax: "$7,800.00",
      netTotal: "$96,400.00",
      estMargin: "$23,136.00",
      marginPercentage: "24%",
    },
    workflow: [
      {
        stepNumber: 1,
        role: "Sales Manager",
        assignee: "James Carter",
        status: "Completed",
        statusLabel: "Authorized",
      },
      {
        stepNumber: 2,
        role: "Commercial Review",
        assignee: "Elena Rostova",
        status: "Current",
        statusLabel: "Required",
      },
      {
        stepNumber: 3,
        role: "VP Finance",
        assignee: "Marcus Vance",
        status: "Pending",
        statusLabel: "Pending",
      },
    ],
    history: [
      {
        id: "hist-4",
        time: "11:46 AM",
        description: "Submitted for commercial approval with Net 90 exception.",
      },
    ],
  },
  {
    id: "appr-1045",
    dealId: "Q-1045",
    customer: "Helix Systems",
    customerGlobalId: "HX-33104",
    value: "$142,000.00",
    rawNumericValue: 142000,
    riskScore: 61,
    riskCategory: "High",
    currentStage: "Finance Review",
    submittedTimeAgo: "1 hour ago",
    submittedExactTime: "11:14 AM",
    status: "Awaiting Review",
    priority: "High",
    requestedBy: {
      name: "Rachel Kim",
      role: "Strategic Accounts Lead",
    },
    reasons: [
      {
        id: "rs-5",
        title: "Hardware Volume Discount Exceeded",
        requestedValue: "22%",
        allowedLimit: "15%",
        exceptionText: "7% above maximum authorized volume tier",
        severity: "high",
      },
    ],
    financials: {
      subtotal: "$182,000.00",
      discount: "-$40,000.00",
      estimatedTax: "$11,200.00",
      netTotal: "$142,000.00",
      estMargin: "$45,440.00",
      marginPercentage: "32%",
    },
    workflow: [
      {
        stepNumber: 1,
        role: "Sales Director",
        assignee: "Rachel Kim",
        status: "Completed",
        statusLabel: "Authorized",
      },
      {
        stepNumber: 2,
        role: "Finance Review",
        assignee: "Marcus Vance",
        status: "Current",
        statusLabel: "Required",
      },
    ],
    history: [
      {
        id: "hist-5",
        time: "11:14 AM",
        description: "Hardware tier discount escalation triggered.",
      },
    ],
  },
  {
    id: "appr-1038",
    dealId: "Q-1038",
    customer: "Globex Industries",
    customerGlobalId: "GX-77218",
    value: "$126,000.00",
    rawNumericValue: 126000,
    riskScore: 54,
    riskCategory: "Medium",
    currentStage: "Sales Review",
    submittedTimeAgo: "2 hours ago",
    submittedExactTime: "10:15 AM",
    status: "Pending",
    priority: "Medium",
    requestedBy: {
      name: "Marcus Miller",
      role: "Senior Account Exec",
    },
    reasons: [
      {
        id: "rs-6",
        title: "Custom SLA Clause Addition",
        requestedValue: "99.99%",
        allowedLimit: "99.9%",
        exceptionText: "Four-nines availability requiring dedicated engineering signoff",
        severity: "warning",
      },
    ],
    financials: {
      subtotal: "$140,000.00",
      discount: "-$14,000.00",
      estimatedTax: "$9,800.00",
      netTotal: "$126,000.00",
      estMargin: "$47,880.00",
      marginPercentage: "38%",
    },
    workflow: [
      {
        stepNumber: 1,
        role: "Sales Review",
        assignee: "James Carter",
        status: "Current",
        statusLabel: "In Progress",
      },
    ],
    history: [
      {
        id: "hist-6",
        time: "10:15 AM",
        description: "Marcus Vance requested changes to Q-1038 regarding SLA clause.",
      },
    ],
  },
  {
    id: "appr-1048",
    dealId: "Q-1048",
    customer: "Northwind Solutions",
    customerGlobalId: "NW-44129",
    value: "$67,500.00",
    rawNumericValue: 67500,
    riskScore: 48,
    riskCategory: "Medium",
    currentStage: "Finance Review",
    submittedTimeAgo: "3 hours ago",
    submittedExactTime: "9:20 AM",
    status: "Pending",
    priority: "Medium",
    requestedBy: {
      name: "Sarah Lin",
      role: "Account Executive",
    },
    reasons: [
      {
        id: "rs-7",
        title: "Annual Upfront Discount Prepayment",
        requestedValue: "12%",
        allowedLimit: "8%",
        exceptionText: "Prepayment rebate adjustment required",
        severity: "warning",
      },
    ],
    financials: {
      subtotal: "$76,700.00",
      discount: "-$9,200.00",
      estimatedTax: "$5,400.00",
      netTotal: "$67,500.00",
      estMargin: "$23,625.00",
      marginPercentage: "35%",
    },
    workflow: [
      {
        stepNumber: 1,
        role: "Sales Manager",
        assignee: "James Carter",
        status: "Completed",
        statusLabel: "Authorized",
      },
      {
        stepNumber: 2,
        role: "Finance Review",
        assignee: "Marcus Vance",
        status: "Current",
        statusLabel: "Required",
      },
    ],
    history: [
      {
        id: "hist-7",
        time: "9:20 AM",
        description: "Submitted for prepayment rate exception.",
      },
    ],
  },
  {
    id: "appr-1031",
    dealId: "Q-1031",
    customer: "Nova Systems",
    customerGlobalId: "NV-10842",
    value: "$54,200.00",
    rawNumericValue: 54200,
    riskScore: 41,
    riskCategory: "Medium",
    currentStage: "Commercial Review",
    submittedTimeAgo: "4 hours ago",
    submittedExactTime: "8:05 AM",
    status: "Pending",
    priority: "Medium",
    requestedBy: {
      name: "James Carter",
      role: "Sales Manager",
    },
    reasons: [
      {
        id: "rs-8",
        title: "Customer Counteroffer Review",
        requestedValue: "3-Yr Fixed",
        allowedLimit: "1-Yr CPI",
        exceptionText: "Multi-year price lock requested without indexation",
        severity: "warning",
      },
    ],
    financials: {
      subtotal: "$60,000.00",
      discount: "-$5,800.00",
      estimatedTax: "$4,200.00",
      netTotal: "$54,200.00",
      estMargin: "$21,680.00",
      marginPercentage: "40%",
    },
    workflow: [
      {
        stepNumber: 1,
        role: "Commercial Review",
        assignee: "Elena Rostova",
        status: "Current",
        statusLabel: "Pending",
      },
    ],
    history: [
      {
        id: "hist-8",
        time: "8:05 AM",
        description: "Customer counteroffer received and routed to Commercial Governance.",
      },
    ],
  },
];
